version: "3"
services:
  db:
    container_name: db_mysql
    build: ./mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: true
      MYSQL_DATABASE: projekt
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      java_app:
        ipv4_address: 123.30.0.5

  server:
    container_name: server_spring
    build: ./server/
    ports:
      - "8080:8080"
    environment:
      DB_HOST: 123.30.0.5
    networks:
      java_app:
        ipv4_address: 123.30.0.10
    depends_on:
      - db

  client:
    container_name: client_react
    build: ./client
    ports:
      - "80:80"
    volumes:
      - ./client/src/:/app/src
    networks:
      java_app:
        ipv4_address: 123.30.0.15
    depends_on:
      - db

networks:
  java_app:
    driver: bridge
    ipam:
      config:
        - subnet: 123.30.0.0/16
          gateway: 123.30.0.1
volumes:
  db_data: